import {GoogleSpreadsheet} from "google-spreadsheet";
import {GOOGLE_SHEET_ID} from "@/configs/config";
import {JWT} from "google-auth-library";
import logging from "@/utils/logging";

let databaseInstance: GoogleSpreadsheet;

export function initDatabase() {
	if (databaseInstance) return;
	try {
		const serviceAccountAuth = new JWT({
			// env var values here are copied from service account credentials generated by google
			// see "Authentication" section in docs for more info
			email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
			key: process.env.GOOGLE_PRIVATE_KEY,
			scopes: ['https://www.googleapis.com/auth/spreadsheets'],
		});

		databaseInstance = new GoogleSpreadsheet(GOOGLE_SHEET_ID, serviceAccountAuth);

		logging.log("Google Sheets database initialized");
	} catch (error) {
		logging.error(error);
	}
}

export function getDatabaseInstance() {
	if (!databaseInstance) {
		initDatabase();
	}
	return databaseInstance;
}